### PR TITLE
fix(sqlite): fix returning sqlite and add tests for support sqlite

### LINKED ISSUE #58: node-sqlite3 does not currently support RETURNING clause
**Describe the bug**
The method insert used inside herbs2knex has the `returning `clause wich is not supported by sqllite3. So calling the insert method the inserted id not returns

**Expected behavior**
The id of the inserted objects should return

I'm using this config:

```
 client: 'sqlite3',
    connection: { filename: "file:memDb1?mode=memory&cache=shared" },
    useNullAsDefault: true,
    migrations: {
      directory: './src/infra/db/migrations',
      tableName: 'knex_migrations'
    }


```

### PR DESCRIPTION
**Pull request by jhomarolo**
fix #58

Fixes #

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request
- [ ] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

File: src/repository.js [hunk 1]
```diff
@@ -187,6 +187,12 @@ module.exports = class Repository {
       .returning(fields)
       .insert(payload)
 
+    //.returning() is not supported by sqlite3 and will not have any effect, so we have to get last inserted row
+    if (this.runner().client && this.runner().client.driverName && (this.runner().client.driverName.includes('sqlite3'))) {
+      const lastInsertedID = await this.knex.raw(`SELECT last_insert_rowid();`)
```
Comment (dalssoft) [inline src/repository.js:192]: Given the async nature of the queries (`.insert(payload)` and `knex.raw('SELECT last_insert_rowid();')` ) it seems it could happen a race condition here: the returned value for `last_insert_rowid()` would be from a different insert, from a different event loop.

Event Loop A: Insert X
Event Loop B: Insert Y
Event Loop A: get `last_insert_rowid` = Y, but should be X

File: src/repository.js [hunk 2]
```diff
@@ -187,6 +187,12 @@ module.exports = class Repository {
...
+      return await this.findByID(lastInsertedID[0]["last_insert_rowid()"])
```
Comment (dalssoft) [inline src/repository.js:193]: `this.findByID` expect a id(s) from the entity. A "domain" ID.

`last_insert_rowid` return the PK only if (1) it exists a PK, (2) if it is a integer [1] and (3) if it is not composed PK. Otherwise it returns a number not related to a "domain" ID.

So, the current implementation seems very error-prone. Is this the only method to return the entity? 

Suggestion: 
If the insertion does not return a error, use the known IDs of the inserted record to retrieve the record.


[1] from [doc](https://www.sqlite.org/c3ref/last_insert_rowid.html): If the table has a column of type [INTEGER PRIMARY KEY](https://www.sqlite.org/lang_createtable.html#rowid) then that column is another alias for the rowid.

Comment (jhomarolo) [reply src/repository.js:193]: I'm aware (also working on it) of this possible bug and will fix it ASAP.

File: src/repository.js (hunk 1 above)
Comment (jhomarolo) [reply src/repository.js:192]: You're right.

We should isolate this in some kind of transaction (http://knexjs.org/guide/transactions.html). I`ll open an issue about this.

File: src/repository.js [hunk 3]
```diff
@@ -187,6 +187,12 @@ module.exports = class Repository {
       .returning(fields)
       .insert(payload)
 
+    //.returning() is not supported by sqlite3 and will not have any effect, so we have to get last inserted row
+    if (this.runner().client && this.runner().client.driverName && (this.runner().client.driverName.includes('sqlite3'))) {
```
[the remark this answers is not in the document]
Comment (jhomarolo) [reply src/repository.js:191]: No there is'not. (https://github.com/knex/knex/blob/49ea2b5fa9068cc15aae94258fae673379127d9d/lib/dialects/sqlite3/index.js#L196
)

But SQLLite now supports returning and should be included in knex soon. (https://github.com/knex/knex/issues/4370)

[the remark this answers is not in the document]
Comment (jhomarolo) [reply src/repository.js:191]: Done. https://github.com/herbsjs/herbs2knex/pull/65/files#diff-c6c5640c6c88a25e77c42e8f3cc7c2ec49c92e8cd6010ca157fe7f1a7f0f55d6
